### ISSUE TITLE
登录了十分钟左右 没点开干 出现报错

### ISSUE THREAD

**Issue by bossoftheworld** [qhgz2013/FuckJW2005#1]
![xbbc 73w6c4zbxdtud4dpl](https://user-images.githubusercontent.com/37247388/37244365-eb5310ee-24c2-11e8-88db-6c0f6d04dfb8.png)

**Comment by qhgz2013** [comment]
您所反应的错误已经成功在最新版本中修复，请您在Release页下选择最新的版本进行下载使用，如果成功解决问题，则可以关闭该issue。若在最新版本中有任何使用问题，也可以创建新的issue反馈。
