### ISSUE TITLE
想抢的课显示时间冲突，然而该时间段我并没有课

### ISSUE THREAD

**Issue by miulmiull** [qhgz2013/FuckJW2005#2]
![1520834216 1](https://user-images.githubusercontent.com/26904730/37267820-8e7a4f86-25fd-11e8-9400-d259493b03c0.png)

**Comment by qhgz2013** [comment]
你好，欢迎反映使用问题。
请您能提供一下用浏览器登录教务系统进行选课之后的截图吗？比如弹出“课程没有余量”或是上面的“上课时间冲突”之类的对话框，以便确定问题出在哪里

**Comment by miulmiull** [comment]
![image](https://user-images.githubusercontent.com/26904730/37278953-47a79ec0-2624-11e8-9379-97637716e59e.png)

**Comment by miulmiull** [comment]
就是一般显示的那样

**Comment by miulmiull** [comment]
试过好几个之后发现如果同一门课同一个老师不同时间段就会出现这样的情况，同一门课一个老师没有多个时间就会正常显示人数超过限制

**Comment by qhgz2013** [comment]
你好，该问题已经在最新版本中修复，下载并使用最新的版本即可。若该问题不再出现，则可以关闭该issue。祝抢课顺利~

**Comment by miulmiull** [comment]
非常感谢！已经抢到课了！
